.catalog:
  name: "Rancher GlusterFS"
  version: 0.0.1
  description: |
    Docker volume plugin for GlusterFS
  minimum_rancher_version: v1.6.4-rc1
  questions:
  - variable: "GLUSTER_SERVER"
    description: "IP or hostname of the default GlusterFS Server"
    label: "Gluster Server"
    required: true
    type: "string"
  - variable: "GLUSTER_VOLUME_NAME"
    label: "Gluster volume name"
    description: "Gluster volume name"
    type: "string"
    required: true
  - variable: RANCHER_DEBUG
    label: Debug Mode
    type: enum
    description: Enable or disable verbose logging
    default: false
    options:
    - true
    - false
glusterfs-driver:
  storage_driver:
    name: rancher-glusterfs
    scope: environment
    volume_access_mode: multiHostRW
